name: My First Workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: My first job
        run: echo "My first Job in GitHub Actions"

      - name: List files
        run: ls

      - name: Read file
        run: cat README.md